name: Build Plugin

on:
  push:
    branches: [ '*' ]

jobs:
  build-plugin:
    name: Build Monstache Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build plugin
        run: |
          cd /docker/plugin
          chmod +x build.sh
          ./build.sh

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v1
        with:
          name: collection_process-plugin
          path: /docker/plugin/collection_process.so
          retention-days: 90